### ISSUE TITLE
More insights on splitting environments into multiple processes rather than threads?

### ISSUE THREAD

**Issue by astroHaoPeng** [Kirkados/AIAA_GNC_2021#1]
Hi Kirk,

I'm recently studying your papers and codes of the DP4G algorithm. They are pretty well written and documented! Very much appreciated for the sharing.

I wonder if you can share more insights or your consideration about using `multiprocessing.Process()` rather than just `threading.Thread()`. Did you encounter a problem using threads? I'm new to distributed programming, but to my knowledge, I don't see any function that requires a individual process. I mean, there seems no operations involving the efficiency problem caused by GIL (Global Interpreter Lock).

Wish to get your reply. Thanks. 

Best,
Hao

**Comment by Kirkados** [comment]
Hi Hao,

I'm glad you've found my open-sourced code and papers useful :)

Yes, I initially tried to use `threading.Thread` for all my environments, but it turns out that the integrator `scipy.integrate.odeint` cannot have multiple instances in multiple threads. However, it is safe to have one integrator a number of separate processes. See [this question](https://stackoverflow.com/questions/34291639/multiple-scipy-integrate-ode-instances) for additional information.

Another thing: Python has a Global Interpreter Lock (GIL) that only allows one thread to be run at a time. Therefore, on a many-CPU machine, still only just one thread can be run at a time. However, multiple processes are totally independent and can be run simultaneously. See [this post](https://scipy.github.io/old-wiki/pages/ParallelProgramming) for more differences between threads and processes

I hope this helps! Happy coding!

Take care,
Kirk

**Comment by astroHaoPeng** [comment]
Oh, I didn't know that `scipy`'s ode solver won't support multi threads before. That's very helpful experience. Thank you.

After learning about `threading` and `multiprocessing`, my another question is that whether the actors in multiple threads will be affected by the GIL? Especially when that the learner and the actors are governed by the same GIL. 
However, in my test runs, I observe a full usage of my CPU cores. Does this imply that the learner and actors are more I/O-bounded? Or, is there some other reason?

**Comment by astroHaoPeng** [comment]
By the way, do you have any plan to migrate the code to `tensorflow 2`? I'm trying this but my progress is super slow now...

**Comment by Kirkados** [comment]
Hi Hao,

Yes, I believe that the other threads (including the actor and learner) will be affected by the GIL. However, Tensorflow and Numpy are implemented to take advantage of many-core CPUs, so I don't believe you will notice a drop in performance because of the GIL. Since you have full CPU-usage, you are CPU-bound.

I do not plan to migrate to `tensorflow 2` anytime soon. You may find the `tf_upgrade_v2` command [(detailed here)](https://www.tensorflow.org/guide/migrate/upgrade) useful to help with the migration.
